### ISSUE TITLE
Using delayMicroseconds in RTOS cause crashed

### ISSUE THREAD

**Issue by masrodjie** [botofancalin/M5Stack-ESP32-Oscilloscope#1]
Using delayMicroseconds in RTOS cause crashed. You should use vTaskDelay

**Comment by botofancalin** [comment]
Get the latest esp32Arduino then try again. It work's just fine.
vTaskDelay has a resolution of milliseconds at RTOS tick rate of 1000Hz
So vTaskDelay is not an option for microseconds.
